# Generated by Django 3.1.7 on 2021-03-31 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20210331_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='کاربر ها')),
            ],
            options={
                'verbose_name': 'مجموعه',
                'verbose_name_plural': 'مجموعه',
            },
        ),
    ]
