# Generated by Django 3.1.7 on 2021-03-31 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_groupusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuteUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.groupusers')),
            ],
        ),
    ]
