# Generated by Django 3.1.7 on 2021-04-01 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_likesusers_visitsusers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChatTick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان')),
                ('link', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='لینک')),
                ('add_link', models.TextField(blank=True, null=True, unique=True, verbose_name='لینک عضویت')),
                ('on_link', models.IntegerField(choices=[(1, 'عضو شود'), (2, 'مسدود شود'), (3, 'فقط بتواند مشاهده کند'), (4, 'نتواند عضو شود فقط ببیند'), (5, 'مدیر شود')], verbose_name=' درزمان اضافه شدن با لینک')),
                ('on_add_link', models.IntegerField(choices=[(1, 'عضو شود'), (2, 'مسدود شود'), (3, 'فقط بتواند مشاهده کند'), (4, 'لینک از کار بیفتد'), (5, 'مدیر شود')], verbose_name='در زمان اضافه شدن با لینک عضویت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('admin_users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.adminusers', verbose_name='مدیران')),
                ('blocked_users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.blockedusers', verbose_name='مسدود شده ها')),
                ('cancel_users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.cancelusers', verbose_name='افراد ترک کرده')),
                ('mute_users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.muteusers', verbose_name='مشاهده کنندگان')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.groupusers', verbose_name='اعضا')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه ها',
            },
        ),
        migrations.CreateModel(
            name='MessageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('group', models.ManyToManyField(to='ChatTick.Group', verbose_name='گروه')),
                ('like', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.likesusers')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.visitsusers')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پیام گروهی',
                'verbose_name_plural': 'پیام گروهی',
            },
        ),
    ]
